<?php
@session_start();
ob_start();
require_once('class/Conexao.php');
require_once('class/Candidato.php');
require_once('class/Categoria.php');
require_once('class/Helper.php');
require_once('class/Equipe.php');
require_once('class/Vagas.php');
?>